
### getByPatientId
GET http://localhost:5000/booking/patient/PT-71377913?limit=5&page=2

### getByDateBooking
GET http://localhost:5000/booking/date-booking/1111111111 

### getByDoctorId
GET http://localhost:5000/booking/doctor/DT-93825413


### create
POST http://localhost:5000/booking
Content-Type: application/json

{
    "email":"phuanlut0000@gmail.com",
    "patientName":"Pé yêu😘",
    "doctorName":"Nguyễn Đăng Định",
    "value":"07:30 - 08:00",
    "doctorId":"DT-57737467",

    "dateBooking":"1644080400000",
    "reasonExamination":"reasonExamination",
    "patientId":"PT-64395546",
    "timeSlotId":"TL-101217200" 
}

### verify-booking
POST  http://localhost:5000/booking/verify-booking
Content-Type: application/json

{
    "bookingId":"BK-46105963"
}