
### getAll
GET http://localhost:8080/patient

### getId
GET http://localhost:8080/patient/PT-14705825

### Create
POST http://localhost:8080/patient
Content-Type: application/json

{
  "fullName":"Thanh Tuấn",
  "phone": "0999999999",  
  "email": "huy@gmail.com",  
  "address":"Quảng Nam",  
  "date":"2022-01-14",  
  "gender":1,  
  "status":1,  
  "patientHistory": "hh",  
  "image": "hh",  
  "accountId": "AC-37227874"
}

### Update
PUT http://localhost:8080/patient/DT-97507614
Content-Type: application/json

{
  "fullName":"Ngoc Huy",
  "phone": "0999999999",  
  "email": "huy@gmail.com",  
  "address":"Quảng Nam",  
  "date":"2022-01-14",  
  "gender":1,  
  "status":1,  
  "patientHistory": "Nhức răng, ê miệng",  
  "image": "image ",  
  "accountId": "AC-37227874"
}

