
### GetOneSchedule  by workingDay and dockerId
GET http://localhost:8080/schedule/wd-dt/check HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiJBQy0zOTk5Nzg1OCIsImlhdCI6MTY0MjEyOTk2MiwiZXhwIjoxNjQyMTMzNTYyfQ.4WloRPl6hHpHLjsuYgKZ2OceXTS_ib2kJ5ZJi-xTVFA

{
  "workingDay": "1642018095",
  "doctorId":"DT-8776823"
}


### Create Schedule
POST http://localhost:8080/schedule HTTP/1.1
content-Type: application/json

{
  "workingDay": "2222222222",
  "startTime": 7,
  "endTime": 8,
  "priceTimeSlot": 10000,
  "maxNumberTimeSlot": 2,
  "rangeTime": 0.5,
  "arrSchedule": [
    {
      "orderIndex": 0,
      "value": "07:00 - 07:30",
      "status": 1
    },
    {
      "orderIndex": 1,
      "value": "07:30 - 08:00",
      "status": 1
    }
  ],
  "doctorId":"DT-8776823",
  "id": "SD-36325781",
  "status": 1
}