
### GetOneSchedule  by workingDay and dockerId
GET http://localhost:8080/schedule/ HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiJBQy04MTU2ODA4MyIsImlhdCI6MTY0MjE2OTc5MSwiZXhwIjoxNjQyMTczMzkxfQ.m8Vs52X_3XdbGSnh8NAPVzhQKgSSuQ6WHgae2flbdcc

{
  "workingDay": "2222222222",
  "doctorId":"DT-69657815"
}


### Create Schedule
POST http://localhost:8080/schedule HTTP/1.1
content-Type: application/json

{
  "workingDay": "555555555",
  "startTime": 7,
  "endTime": 8,
  "priceTimeSlot": 10000,
  "maxNumberTimeSlot": 5,
  "rangeTime": 0.5,
  "arrSchedule": [
    {
      "orderIndex": 0,
      "value": "07:00 - 07:30",
      "status": 1
    },
    {
      "orderIndex": 1,
      "value": "07:30 - 08:00",
      "status": 1
    },
    {
      "orderIndex": 2,
      "value": "08:00 - 08:30",
      "status": 1
    },
    {
      "orderIndex": 3,
      "value": "08:30 - 09:00",
      "status": 1
    }
  ],
  "doctorId":"DT-46979565",
  "status": 1
}

### Update Schedule
PUT http://localhost:8080/schedule/
content-Type: application/json

{
  "workingDay": "555555555",
  "startTime": 7,
  "endTime": 8,
  "priceTimeSlot": 10000,
  "maxNumberTimeSlot": 5,
  "rangeTime": 0.5,
  "arrSchedule": [
    {
      "orderIndex": 0,
      "value": "07:00 - 07:30",
      "status": 1
    },
    {
      "orderIndex": 1,
      "value": "07:30 - 08:00",
      "status": 1
    }
  ],
  "doctorId":"DT-28147879",
  "status": 1
}